version: '3.9'

services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ingestion_service:
    build: .
    container_name: rust_tcp_ingestion
    ports:
      - "7878:7878"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    restart: on-failure

volumes:
  mongo_data:
